name: Thomas A. Anderson
# Info to show in header
email: neo@zion.gov
phone: (312) 555-0690
location: Zion, Earth
# Header introduction / mission statement
intro: I carry the Matrix's source code, known as the Prime Program. This gives me the ability to freely manipulate the simulated reality of the Matrix, similar to the authority a system administrator has over a given system. I manifest these abilities as various superhuman powers.
#for Twitter cards:
twitter: '@neo'
# Removing all proficiencies will remove the section from the resume
proficiencies:
  # - list item
  - Hacking
  - Creative entrepeneurship
  - Martial arts
  - Negotiations
  - Hovercraft piloting
# Links to include in header
links:
  # text: http://link.com
  '@neo': https://github.com/neo

just: "write some"
meta: 
  [
    {
      content: "text/html; charset=utf-8",
      http-equiv: "Content-Type"
    },
    {
      content: "width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0"
    },
    {
      content: "Responsive One Page Vcard Portfolio or Resume Template",
      name: "description"
    },
    {
      content: "TheThemeLab",
      name: "author"
    }
  ]

# OLD site.yaml STUFF
# SEO / <meta> tag information
title: The Resume of Thomas A. Anderson (The One)
description: Prophesized by The Oracle to be The One, Thomas A. Anderson freed humanity from the Matrix and ended the Machine War.
# theme color for header, borders, section headings
# For best results, choose a color that has a color ratio of at least 3.5
# against white. Otherwise, all text etc is set to black to preserve readability
# @link http://leaverou.github.io/contrast-ratio/
theme: '#0074D9'
# of work experiences to show
jobs: 3
# of educational experiences to show
schools: 1
# show 'References available' link in footer
references: true
# Remove theme color on print
printstyles: false
# Show promo link under resume (you probably want to set this to false)
promolink: true