# Any "technical" settings should be stored here (Basically, any 
# settings or limitations that aren't commonly changed or even 
# paid attention to)
---
general:
  title_prefix: Resume of the great JUSTIN HYLAND
meta:
  description:
    length_units: chars
    # Recommended 155 char length
    length: '155'
  keywords:
    length_units: words
    # Recommended 25 word length
    length: '25'
template:
  buttons:
    types: ['default','primary','success','info','warning','danger','link']
    sizes: ['lg','md','sm','xs']
# Default values for any mixins or functions
defaults:
  button_icon_location: 'left'